"""Real content ingestion for learner-facing L/S/R/W material.

No sample German content is stored in source code.

Listening:
  Fetches real Deutsche Welle podcast episodes, downloads audio locally,
  and uses local Whisper to create a transcript. Items remain pending.

Speaking:
  Ingests a locally downloaded Common Voice German dataset. This avoids
  relying on an undocumented/unstable web endpoint. Common Voice provides
  validated voice clips and associated sentence metadata.

Reading/Writing:
  Generated by local Ollama model and stored pending; use generate_reading.py
  or the Content Manager endpoint.
"""
import argparse
import csv
import hashlib
import os
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

import requests
from sqlalchemy.orm import Session

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from app.db.base import SessionLocal, Base, engine
from app.models.db_models import ContentItem, Skill, CEFRLevel
from app.services.listening_service import transcribe_audio
try:
    from content.generate_reading import generate_one, create_item
except ImportError:
    from generate_reading import generate_one, create_item


DW_FEED_URL = "https://rss.dw.com/xml/DKpodcast_lgn_de"


def ingest_listening_from_dw(db: Session, level: CEFRLevel, limit: int) -> int:
    resp = requests.get(DW_FEED_URL, timeout=30)
    resp.raise_for_status()
    root = ET.fromstring(resp.content)
    items = root.findall(".//item")[:limit]
    audio_dir = Path(__file__).resolve().parent / "audio" / "dw"
    audio_dir.mkdir(parents=True, exist_ok=True)

    count = 0
    for index, item in enumerate(items):
        enclosure = item.find("enclosure")
        audio_url = enclosure.get("url") if enclosure is not None else None
        if not audio_url:
            continue

        safe_name = f"dw_{hashlib.sha256(audio_url.encode()).hexdigest()[:16]}.mp3"
        audio_path = audio_dir / safe_name
        if db.query(ContentItem).filter(ContentItem.audio_path == str(audio_path.resolve())).first():
            continue
        audio_resp = requests.get(audio_url, timeout=60)
        audio_resp.raise_for_status()
        audio_path.write_bytes(audio_resp.content)

        try:
            transcript = transcribe_audio(str(audio_path))
        except Exception as exc:
            print(f"Skipping DW episode {index}: local Whisper failed: {exc}")
            audio_path.unlink(missing_ok=True)
            continue

        db.add(ContentItem(
            skill=Skill.listening,
            level=level,
            text_content=transcript,
            audio_path=str(audio_path.resolve()),
            source="Deutsche Welle - Langsam gesprochene Nachrichten; transcript=local Whisper",
            reviewed="pending",
        ))
        count += 1

    db.commit()
    print(f"Ingested {count} real listening items at {level.value}, status=pending")
    return count


def _find_common_voice_tsv(root: Path) -> Path:
    candidates = [
        root / "validated.tsv", root / "train.tsv", root / "dev.tsv", root / "test.tsv",
        root / "1781690474638-sps-corpus-4.0-2026-06-12-de" / "sps-corpus-4.0-2026-06-12-de" / "ss-corpus-de.tsv",
        root / "ss-corpus-de.tsv"
    ]
    for candidate in candidates:
        if candidate.is_file():
            return candidate
    raise FileNotFoundError(f"No TSV found under {root}")


def ingest_speaking_from_commonvoice(db: Session, level: CEFRLevel, limit: int, dataset_dir: str) -> int:
    root = Path(dataset_dir).expanduser().resolve()
    tsv_path = _find_common_voice_tsv(root)
    clips_dir = root / "clips"
    if not clips_dir.is_dir():
        clips_dir = root  # fallback to root directory if no clips dir
        
    count = 0
    with tsv_path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f, delimiter="\t")
        for row in reader:
            if count >= limit:
                break
            sentence = (row.get("sentence") or row.get("transcription") or "").strip()
            path_value = (row.get("path") or row.get("audio_file") or "").strip()
            if not sentence or not path_value:
                continue
            
            # Find the actual audio file
            source_audio = (clips_dir / path_value).resolve()
            if not source_audio.is_file():
                # Check inner audios folder as fallback
                fallback_audio = (root / "1781690474638-sps-corpus-4.0-2026-06-12-de" / "sps-corpus-4.0-2026-06-12-de" / "audios" / path_value).resolve()
                if fallback_audio.is_file():
                    source_audio = fallback_audio
                else:
                    continue
                    
            if db.query(ContentItem).filter(ContentItem.audio_path == str(source_audio)).first():
                continue

            db.add(ContentItem(
                skill=Skill.speaking,
                level=level,
                text_content=sentence,
                audio_path=str(source_audio),
                source="Custom/Common Voice German dataset",
                reviewed="pending",
            ))
            count += 1

    db.commit()
    print(f"Ingested {count} real speaking reference clips at {level.value}, status=pending")
    return count


def generate_text_content(db: Session, level: CEFRLevel, limit: int):
    total = 0
    for skill in (Skill.reading, Skill.writing):
        for index in range(limit):
            try:
                db.add(create_item(skill, level, generate_one(skill, level)))
                total += 1
            except Exception as exc:
                print(f"Generation {skill.value} {index + 1} failed: {exc}")
    db.commit()
    print(f"Generated {total} real reading/writing items at {level.value}, status=pending")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--skill", required=True, choices=["listening", "reading", "writing", "speaking", "all"])
    parser.add_argument("--level", required=True, choices=[l.value for l in CEFRLevel])
    parser.add_argument("--limit", type=int, default=5)
    parser.add_argument("--commonvoice-dir", default=os.environ.get("COMMONVOICE_GERMAN_DIR", ""))
    args = parser.parse_args()

    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    level = CEFRLevel(args.level)
    try:
        if args.skill in ("listening", "all"):
            ingest_listening_from_dw(db, level, args.limit)
        if args.skill == "speaking" or args.skill == "all":
            if not args.commonvoice_dir:
                raise ValueError("Common Voice dataset directory required. Pass --commonvoice-dir PATH.")
            ingest_speaking_from_commonvoice(db, level, args.limit, args.commonvoice_dir)
        if args.skill in ("reading", "writing"):
            for _ in range(args.limit):
                skill = Skill(args.skill)
                db.add(create_item(skill, level, generate_one(skill, level)))
            db.commit()
            print(f"Generated {args.limit} real {args.skill} items at {level.value}, status=pending")
        elif args.skill == "all":
            generate_text_content(db, level, args.limit)
    finally:
        db.close()
