"""
Real human review gate. Content generated by generate_reading.py (or
any future generation script) sits with reviewed="pending" and is
invisible to real learners until a human runs this script and
approves or rejects each item. This is the actual enforcement of
"no hardcoding, no fake content" for LLM-generated material — a human
checks it's real, correct German before it ever reaches a learner.

Usage:
    python review_queue.py
"""
import os
import sys
import json

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from app.db.base import SessionLocal, Base, engine
from app.models.db_models import ContentItem

if __name__ == "__main__":
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    pending = db.query(ContentItem).filter(ContentItem.reviewed == "pending").all()

    if not pending:
        print("Nothing pending review.")
        sys.exit(0)

    print(f"{len(pending)} items pending review.\n")
    for item in pending:
        print("=" * 60)
        print(f"ID {item.id} | {item.skill.value} | {item.level.value} | source: {item.source}")
        print(f"\n{item.text_content}\n")
        if item.answer_key:
            ak = json.loads(item.answer_key)
            for q, a in ak.items():
                print(f"  Q: {q}\n  A: {a}")
        choice = input("\n[a]pprove / [r]eject / [s]kip for later? ").strip().lower()
        if choice == "a":
            item.reviewed = "approved"
            db.commit()
            print("Approved — now visible to real learners.")
        elif choice == "r":
            item.reviewed = "rejected"
            db.commit()
            print("Rejected — will not be shown, kept in DB for audit.")
        else:
            print("Skipped.")

    db.close()
